// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdMqfbISGTMtRbjpn80RkDWw7cLE89H8o',
    appId: '1:1095082345896:web:3e47e3a801acd6358c099d',
    messagingSenderId: '1095082345896',
    projectId: 'to-do-firestore-bdb67',
    authDomain: 'to-do-firestore-bdb67.firebaseapp.com',
    storageBucket: 'to-do-firestore-bdb67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SAHaHqxU9qchZeveV-FICyHUEujVoD4',
    appId: '1:1095082345896:android:6ccb1505a2bbba2e8c099d',
    messagingSenderId: '1095082345896',
    projectId: 'to-do-firestore-bdb67',
    storageBucket: 'to-do-firestore-bdb67.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdMqfbISGTMtRbjpn80RkDWw7cLE89H8o',
    appId: '1:1095082345896:web:9faa071989e8b0d88c099d',
    messagingSenderId: '1095082345896',
    projectId: 'to-do-firestore-bdb67',
    authDomain: 'to-do-firestore-bdb67.firebaseapp.com',
    storageBucket: 'to-do-firestore-bdb67.firebasestorage.app',
  );
}
